name: qiime2-pipeline
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Core dependencies
  - python=3.8
  - qiime2=2023.5
  - q2-dada2=2023.5
  - q2-deblur=2023.5
  - q2-feature-classifier=2023.5
  - q2-phylogeny=2023.5
  - q2-diversity=2023.5
  - q2-composition=2023.5
  - q2-taxa=2023.5
  - snakemake=7.0
  
  # Python packages
  - biopython=1.79
  - pandas=1.5.0
  - numpy=1.23.0
  - scikit-learn=1.0.2
  - scikit-bio=0.5.7
  
  # R packages
  - r-base=4.1
  - r-tidyverse=1.3.1
  - bioconductor-deseq2=1.34.0
  - bioconductor-phyloseq=1.38.0
  - r-biomformat=1.22.0
  
  # Additional tools
  - lefse=1.1.2
  - wget
  - biom-format=2.1.10
  
  # For visualization
  - r-ggplot2=3.3.5
  - r-reshape2=1.4.4
  - r-vegan=2.5_7
  
  # Pip packages
  - pip
  - pip:
    - q2-lefse==0.1.0


